### ISSUE TITLE
Fix deployment of master branch

### ISSUE THREAD

**Issue by ricardoromanj** [rjricardo/misas#17]
The database is being dumped and recreated each time.
Evaluate necessity of exposing ports, it may not be needed.

**Comment by ricardoromanj** [comment]
The database is only being destroyed and recreated on test version of app. Still need to review about ports.

**Comment by victor-fdez** [comment]
Is this already fixed @roman0316

**Comment by ricardoromanj** [comment]
Ir should have as far as I am concerned.

On Tuesday, May 17, 2016, Victor Fernandez notifications@github.com wrote:

> Is this already fixed @roman0316 https://github.com/roman0316
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/roman0316/misas/issues/17#issuecomment-219759653

## 

  Ricardo Román | _INT_
| r.rmn92@gmail.com |

**Comment by victor-fdez** [comment]
Ok, podemos probar esto cuando acabemos este milestone.
