### ISSUE TITLE
Develop parsing solution

### ISSUE THREAD

**Issue by ricardoromanj** [rjricardo/misas#2]
Develop parsing solution for bringing in the data to mongodb.

**Comment by victor-fdez** [comment]
I have been looking around this morning, we currently have two options.
1. Get mas information from quieroiramisa.com. In this case we would need to use the google calendar javascript API or try to decipher the urls and their meaning to retrieve masses for the city of Juarez. The option to me seems a little limited and if we go the difficult way of trying to decipher the urls... it will be more difficult.
2. Get mas information from dondeahimisa.com. This webpage is much more complete in that includes masses for the whole country of Mexico. Developing a parsing solution for this webpage would really payoff as it would allow us show masses for all of cities in Mexico. This webpage is written in ASP.NET and it looks like they are not checking requests very well, also their URLS seem simple at the moment, but I need to investigate this further.

I also have included some interesting links, that might be helpful later on.... if you find more interesting stuff please post it here.

MAP OF ALL CHURCHES IN JUAREZ
https://www.google.com/maps/d/u/0/viewer?mid=zRZ2EOOG55O0.kTBtpJBqXHT4
DIRECTORIO DE PARROQUIAS
http://diocesisdeciudadjuarez.org/parroquias/

**Comment by ricardoromanj** [comment]
Getting the information from dondehaymisa.com seems to be the correct way. It would certainly pay off in the short run. Either way, we cannot trust the data on either site to be current, but it is a good starting point.

Would you consider adding lat/lng to the parroquia model?

**Comment by victor-fdez** [comment]
Yes I think we should add lat/lng to the parroquias model. I also think we
should look at the recurrence model used in outlook (I looked at it today
it was really complete).

**Comment by victor-fdez** [comment]
#19 implements parsing of churches from one of the website mentioned above. The solution is still missing lat/lon parsing but I think we can get those from that same website... we should also try getting images from the website while we are at it. I will try to implement that now.

**Comment by victor-fdez** [comment]
#22 Already contains the parsing solution
